//= require js/vendor/jquery-1.7.2.min
//= require js/vendor/jquery.mobile-1.2.0.min
//= require js/vendor/underscore-min
//= require js/vendor/backbone-min
//= require js/storageManager
//= require js/mapManager
//= require js/locationManager
//= require js/studiosManager
//= require js/views/listItemView
//= require js/views/listView
//= require js/views/titleView
//= require js/router
//= require js/my
//= require_self